apiVersion: v1
kind: Secret
data:
  password: cGFzc3dvcmQK
  username: ZGF0YWRvZw==
metadata:
  creationTimestamp: null
  name: datadog-user
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: datadog-user
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  tags:
  - monitoring
  rabbitmqClusterReference:
    name: rabbitmq-operator
  importCredentialsSecret:
    name: datadog-user
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: datadog-user-permissions
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vhost: "/"
  user: "datadog"
  permissions:
    write: "^amq\\.default$"
    configure: "^aliveness-test$"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-operator
---
