---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin-user
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: rabbitmq-user
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: admin-permissions
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vhost: "/"
  user: "admin"
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
